import { FoodItem, FoodType, FoodCategory, User, UserRole } from './types';

export const MOCK_USERS: User[] = [
  { id: '1', email: 'student@canteenx.com', role: UserRole.STUDENT, name: 'Alex Doe' },
];

export const MOCK_FOOD_ITEMS: FoodItem[] = [
  {
    id: 1,
    name: "Classic Veggie Burger",
    description: "A delicious and juicy vegetable patty burger with fresh lettuce, tomatoes, and our secret sauce.",
    price: 120,
    image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.SANDWICH, FoodCategory.POPULAR],
    rating: 4.5,
    nutrition: { calories: 350, protein: 15, carbs: 40 },
    inStock: true,
  },
  {
    id: 2,
    name: "Grilled Chicken Salad",
    description: "Healthy and refreshing salad with grilled chicken breast, mixed greens, cherry tomatoes, and a light vinaigrette.",
    price: 180,
    image: "https://images.unsplash.com/photo-1551248429-42971d15c8ab?q=80&w=800&auto=format&fit=crop",
    type: FoodType.NON_VEG,
    category: [FoodCategory.SALAD, FoodCategory.POPULAR],
    rating: 4.8,
    nutrition: { calories: 280, protein: 30, carbs: 10 },
    inStock: true,
  },
  {
    id: 3,
    name: "Margherita Pizza",
    description: "Classic pizza with fresh mozzarella, basil, and a rich tomato sauce on a thin crust.",
    price: 250,
    image: "https://images.unsplash.com/photo-1594007654729-407eedc4be65?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.MAIN_COURSE, FoodCategory.SPECIAL],
    rating: 4.6,
    nutrition: { calories: 600, protein: 25, carbs: 70 },
    inStock: true,
  },
  {
    id: 4,
    name: "Spicy Chicken Wings",
    description: "Crispy and spicy chicken wings tossed in a tangy buffalo sauce, served with a side of ranch.",
    price: 200,
    image: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?q=80&w=800&auto=format&fit=crop",
    type: FoodType.NON_VEG,
    category: [FoodCategory.SIDES, FoodCategory.POPULAR],
    rating: 4.7,
    nutrition: { calories: 450, protein: 35, carbs: 5 },
    inStock: false,
  },
  {
    id: 5,
    name: "Paneer Tikka Masala",
    description: "Creamy and flavorful curry with grilled paneer cubes, served with a side of basmati rice.",
    price: 220,
    image: "https://images.unsplash.com/photo-1630617383931-a7a7ddc0aa6a?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.MAIN_COURSE],
    rating: 4.9,
    nutrition: { calories: 550, protein: 20, carbs: 50 },
    inStock: true,
  },
  {
    id: 6,
    name: "Chicken Club Sandwich",
    description: "A triple-decker sandwich with layers of grilled chicken, bacon, lettuce, tomato, and mayonnaise.",
    price: 150,
    image: "https://images.unsplash.com/photo-1592415486689-125c93582314?q=80&w=800&auto=format&fit=crop",
    type: FoodType.NON_VEG,
    category: [FoodCategory.SANDWICH, FoodCategory.SPECIAL],
    rating: 4.4,
    nutrition: { calories: 500, protein: 28, carbs: 45 },
    inStock: true,
  },
  {
    id: 7,
    name: "Fresh Orange Juice",
    description: "100% pure and freshly squeezed orange juice, packed with Vitamin C.",
    price: 80,
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.BEVERAGE],
    rating: 4.9,
    nutrition: { calories: 120, protein: 2, carbs: 28 },
    inStock: true,
  },
  {
    id: 8,
    name: "Caesar Salad",
    description: "Crisp romaine lettuce, parmesan cheese, crunchy croutons, and a creamy Caesar dressing.",
    price: 160,
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.SALAD],
    rating: 4.3,
    nutrition: { calories: 250, protein: 8, carbs: 20 },
    inStock: true,
  },
  {
    id: 9,
    name: "Samosa (2 Pcs)",
    description: "Crispy pastry filled with spiced potatoes and peas, a perfect tea-time snack.",
    price: 40,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70b50?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.SIDES, FoodCategory.POPULAR],
    rating: 4.8,
    nutrition: { calories: 260, protein: 5, carbs: 35 },
    inStock: true,
  },
  {
    id: 10,
    name: "Masala Dosa",
    description: "A thin, crispy crepe made from fermented rice and lentil batter, filled with a savory potato mash.",
    price: 90,
    image: "https://images.unsplash.com/photo-1668665553138-20b1a4730f81?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.MAIN_COURSE, FoodCategory.SPECIAL],
    rating: 4.9,
    nutrition: { calories: 380, protein: 8, carbs: 65 },
    inStock: true,
  },
  {
    id: 11,
    name: "Chole Bhature",
    description: "A combination of spicy chickpeas and fluffy, deep-fried bread. A classic North Indian dish.",
    price: 110,
    image: "https://images.unsplash.com/photo-1604383186243-71b5a51e6c35?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.MAIN_COURSE, FoodCategory.POPULAR],
    rating: 4.7,
    nutrition: { calories: 700, protein: 18, carbs: 90 },
    inStock: true,
  },
  {
    id: 12,
    name: "Chicken Biryani",
    description: "Aromatic basmati rice cooked with succulent chicken pieces and a blend of traditional spices.",
    price: 180,
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?q=80&w=800&auto=format&fit=crop",
    type: FoodType.NON_VEG,
    category: [FoodCategory.MAIN_COURSE, FoodCategory.POPULAR],
    rating: 4.9,
    nutrition: { calories: 650, protein: 35, carbs: 75 },
    inStock: true,
  },
  {
    id: 13,
    name: "Vada Pav",
    description: "A spicy potato fritter sandwiched in a soft bread roll, garnished with chutneys. Mumbai's favorite snack.",
    price: 50,
    image: "https://images.unsplash.com/photo-1627068213620-571f3ea43c2c?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.SANDWICH, FoodCategory.POPULAR],
    rating: 4.8,
    nutrition: { calories: 300, protein: 7, carbs: 50 },
    inStock: true,
  },
  {
    id: 14,
    name: "Veg Thali",
    description: "A complete meal platter with rice, chapati, dal, two vegetable curries, salad, and a sweet.",
    price: 140,
    image: "https://images.unsplash.com/photo-1626781414755-a241a74d5b27?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.MAIN_COURSE],
    rating: 4.6,
    nutrition: { calories: 800, protein: 25, carbs: 120 },
    inStock: true,
  },
  {
    id: 15,
    name: "Cold Coffee",
    description: "A refreshing and creamy cold coffee shake, perfect to beat the heat.",
    price: 70,
    image: "https://images.unsplash.com/photo-1579953935249-c1e1a1793310?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.BEVERAGE],
    rating: 4.5,
    nutrition: { calories: 250, protein: 8, carbs: 35 },
    inStock: true,
  },
  {
    id: 16,
    name: "Masala Chai",
    description: "A hot, aromatic tea brewed with a mix of Indian spices. The perfect pick-me-up.",
    price: 20,
    image: "https://images.unsplash.com/photo-1594233734183-b0724e32d665?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.BEVERAGE, FoodCategory.POPULAR],
    rating: 4.9,
    nutrition: { calories: 80, protein: 2, carbs: 10 },
    inStock: true,
  },
  {
    id: 17,
    name: "Veg Fried Rice",
    description: "Stir-fried rice with a medley of fresh vegetables and a touch of soy sauce.",
    price: 100,
    image: "https://images.unsplash.com/photo-1626385317782-133bbd31061a?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.MAIN_COURSE],
    rating: 4.4,
    nutrition: { calories: 450, protein: 10, carbs: 80 },
    inStock: true,
  },
  {
    id: 18,
    name: "Chilli Chicken Dry",
    description: "A popular Indo-Chinese dish of crispy chicken chunks tossed in a spicy and tangy sauce.",
    price: 160,
    image: "https://images.unsplash.com/photo-1599494112214-e82202656b2f?q=80&w=800&auto=format&fit=crop",
    type: FoodType.NON_VEG,
    category: [FoodCategory.SIDES, FoodCategory.SPECIAL],
    rating: 4.7,
    nutrition: { calories: 500, protein: 30, carbs: 25 },
    inStock: true,
  },
  {
    id: 19,
    name: "Idli Sambar (4 Pcs)",
    description: "Steamed rice and lentil cakes served with a flavorful vegetable and lentil stew.",
    price: 70,
    image: "https://images.unsplash.com/photo-1664420879612-9c869502b704?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.MAIN_COURSE],
    rating: 4.6,
    nutrition: { calories: 300, protein: 10, carbs: 60 },
    inStock: true,
  },
  {
    id: 20,
    name: "Filter Coffee",
    description: "Authentic South Indian filter coffee, strong, aromatic, and frothy.",
    price: 30,
    image: "https://images.unsplash.com/photo-1556485678-c60395c25e8a?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.BEVERAGE],
    rating: 4.8,
    nutrition: { calories: 100, protein: 2, carbs: 12 },
    inStock: true,
  }
];