import { FoodItem, FoodType, FoodCategory, User, UserRole } from './types';

export const MOCK_USERS: User[] = [
  { id: '1', email: 'student@canteenx.com', role: UserRole.STUDENT, name: 'Alex Doe' },
  { id: '2', email: 'staff@canteenx.com', role: UserRole.STAFF, name: 'Jane Smith' },
];

export const MOCK_FOOD_ITEMS: FoodItem[] = [
  {
    id: 1,
    name: "Classic Veggie Burger",
    description: "A delicious and juicy vegetable patty burger with fresh lettuce, tomatoes, and our secret sauce.",
    price: 5.99,
    image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.SANDWICH, FoodCategory.POPULAR],
    rating: 4.5,
    nutrition: { calories: 350, protein: 15, carbs: 40 },
    inStock: true,
  },
  {
    id: 2,
    name: "Grilled Chicken Salad",
    description: "Healthy and refreshing salad with grilled chicken breast, mixed greens, cherry tomatoes, and a light vinaigrette.",
    price: 7.50,
    image: "https://images.unsplash.com/photo-1551248429-42971d15c8ab?q=80&w=800&auto=format&fit=crop",
    type: FoodType.NON_VEG,
    category: [FoodCategory.SALAD, FoodCategory.POPULAR],
    rating: 4.8,
    nutrition: { calories: 280, protein: 30, carbs: 10 },
    inStock: true,
  },
  {
    id: 3,
    name: "Margherita Pizza",
    description: "Classic pizza with fresh mozzarella, basil, and a rich tomato sauce on a thin crust.",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1594007654729-407eedc4be65?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.MAIN_COURSE, FoodCategory.SPECIAL],
    rating: 4.6,
    nutrition: { calories: 600, protein: 25, carbs: 70 },
    inStock: true,
  },
  {
    id: 4,
    name: "Spicy Chicken Wings",
    description: "Crispy and spicy chicken wings tossed in a tangy buffalo sauce, served with a side of ranch.",
    price: 6.75,
    image: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?q=80&w=800&auto=format&fit=crop",
    type: FoodType.NON_VEG,
    category: [FoodCategory.SIDES, FoodCategory.POPULAR],
    rating: 4.7,
    nutrition: { calories: 450, protein: 35, carbs: 5 },
    inStock: false,
  },
  {
    id: 5,
    name: "Paneer Tikka Masala",
    description: "Creamy and flavorful curry with grilled paneer cubes, served with a side of basmati rice.",
    price: 9.50,
    image: "https://images.unsplash.com/photo-1630617383931-a7a7ddc0aa6a?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.MAIN_COURSE],
    rating: 4.9,
    nutrition: { calories: 550, protein: 20, carbs: 50 },
    inStock: true,
  },
  {
    id: 6,
    name: "Chicken Club Sandwich",
    description: "A triple-decker sandwich with layers of grilled chicken, bacon, lettuce, tomato, and mayonnaise.",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1592415486689-125c93582314?q=80&w=800&auto=format&fit=crop",
    type: FoodType.NON_VEG,
    category: [FoodCategory.SANDWICH, FoodCategory.SPECIAL],
    rating: 4.4,
    nutrition: { calories: 500, protein: 28, carbs: 45 },
    inStock: true,
  },
  {
    id: 7,
    name: "Fresh Orange Juice",
    description: "100% pure and freshly squeezed orange juice, packed with Vitamin C.",
    price: 2.50,
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.BEVERAGE],
    rating: 4.9,
    nutrition: { calories: 120, protein: 2, carbs: 28 },
    inStock: true,
  },
  {
    id: 8,
    name: "Caesar Salad",
    description: "Crisp romaine lettuce, parmesan cheese, crunchy croutons, and a creamy Caesar dressing.",
    price: 6.00,
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?q=80&w=800&auto=format&fit=crop",
    type: FoodType.VEG,
    category: [FoodCategory.SALAD],
    rating: 4.3,
    nutrition: { calories: 250, protein: 8, carbs: 20 },
    inStock: true,
  }
];